version: 2

project_name: git-vault

builds:
  - id: git-vault
    main: ./cmd/git-vault
    binary: git-vault
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ducduyn31/git-vault/internal/cli.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
